{
  "info": {
    "contact": {
      "email": "fdxsupport@financialdataexchange.org",
      "name": "Financial Data Exchange",
      "url": "https://financialdataexchange.org/"
    },
    "description": "Financial Data Exchange V6.2.0 Customer API",
    "license": {
      "name": "FDX API License Agreement (11-13-2019)",
      "url": "https://financialdataexchange.org/common/Uploaded%20files/Policies/FDX%20API%20License%20Agreement-(11-13-2019).pdf"
    },
    "title": "FDX V6.2.0 Customer API",
    "version": "6.2.0"
  },
  "openapi": "3.0.3",
  "servers": [
    {
      "url": "http://localhost:8080/fdx"
    },
    {
      "description": "Financial Data Exchange V6 Customer API",
      "url": "http://host.docker.internal:8090/fdxapi"
    }
  ],
  "tags": [
    {
      "description": "Search and view customer or customers",
      "name": "Personal Information"
    }
  ],
  "security": [
    {
      "jwtAuth": []
    }
  ],
  "paths": {
    "/customers": {
      "get": {
        "description": "Retrieve account holders related to permissioned accounts",
        "operationId": "getCustomers",
        "parameters": [
          {
            "$ref": "#/components/parameters/OffsetQuery"
          },
          {
            "$ref": "#/components/parameters/LimitQuery"
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Customers"
                }
              }
            },
            "description": "Customers",
            "headers": {
              "x-fapi-interaction-id": {
                "$ref": "#/components/headers/x-fapi-interaction-id"
              }
            }
          }
        },
        "summary": "Retrieve customers",
        "tags": [
          "Personal Information"
        ]
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/FapiInteractionIdHeader"
        },
        {
          "$ref": "#/components/parameters/FdxApiActorTypeHeader"
        }
      ]
    },
    "/customers/current": {
      "get": {
        "description": "Get information about the customer within the authorization scope",
        "operationId": "getCustomerInfo",
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Customer"
                }
              }
            },
            "description": "Data describing current authenticated customer",
            "headers": {
              "x-fapi-interaction-id": {
                "$ref": "#/components/headers/x-fapi-interaction-id"
              }
            }
          }
        },
        "summary": "Get current authenticated customer information",
        "tags": [
          "Personal Information"
        ]
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/FapiInteractionIdHeader"
        },
        {
          "$ref": "#/components/parameters/FdxApiActorTypeHeader"
        }
      ]
    },
    "/customers/{customerId}": {
      "get": {
        "description": "Retrieve customer information by customer id",
        "operationId": "getCustomer",
        "parameters": [
          {
            "description": "Customer Identifier",
            "in": "path",
            "name": "customerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Customer"
                }
              }
            },
            "description": "Customer",
            "headers": {
              "x-fapi-interaction-id": {
                "$ref": "#/components/headers/x-fapi-interaction-id"
              }
            }
          },
          "404": {
            "content": {
              "application/json": {
                "examples": {
                  "Customer not found": {
                    "value": {
                      "code": "601",
                      "debugMessage": "Provider custom developer-level error details for troubleshooting",
                      "message": "Customer not found"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            },
            "description": "Customer with id not found",
            "headers": {
              "x-fapi-interaction-id": {
                "$ref": "#/components/headers/x-fapi-interaction-id"
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/500"
          },
          "501": {
            "$ref": "#/components/responses/501"
          },
          "503": {
            "$ref": "#/components/responses/503"
          }
        },
        "summary": "Customer by id",
        "tags": [
          "Personal Information"
        ]
      },
      "parameters": [
        {
          "$ref": "#/components/parameters/FapiInteractionIdHeader"
        },
        {
          "$ref": "#/components/parameters/FdxApiActorTypeHeader"
        },
        {
          "in": "path",
          "name": "customerId",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "AccountHolderRelationship": {
        "description": "Types of relationships between accounts and holders. Suggested values",
        "enum": [
          "AUTHORIZED_USER",
          "BUSINESS",
          "FOR_BENEFIT_OF",
          "FOR_BENEFIT_OF_PRIMARY",
          "FOR_BENEFIT_OF_PRIMARY_JOINT_RESTRICTED",
          "FOR_BENEFIT_OF_SECONDARY",
          "FOR_BENEFIT_OF_SECONDARY_JOINT_RESTRICTED",
          "FOR_BENEFIT_OF_SOLE_OWNER_RESTRICTED",
          "POWER_OF_ATTORNEY",
          "PRIMARY",
          "PRIMARY_BORROWER",
          "PRIMARY_JOINT",
          "PRIMARY_JOINT_TENANTS",
          "SECONDARY",
          "SECONDARY_BORROWER",
          "SECONDARY_JOINT",
          "SECONDARY_JOINT_TENANTS",
          "SOLE_OWNER",
          "TRUSTEE",
          "UNIFORM_TRANSFER_TO_MINOR"
        ],
        "title": "Account Holder Relationship",
        "type": "string"
      },
      "ActorType": {
        "description": "Indicates whether a customer is present and has requested the operation (USER), or if a batch job has requested the operation (BATCH)",
        "enum": [
          "BATCH",
          "USER"
        ],
        "title": "FDX API Actor Type",
        "type": "string"
      },
      "Address": {
        "description": "U.S. domestic address or a foreign address with country other than 'US'",
        "properties": {
          "city": {
            "$ref": "#/components/schemas/String64"
          },
          "country": {
            "$ref": "#/components/schemas/Iso3166CountryCode"
          },
          "line1": {
            "$ref": "#/components/schemas/String64"
          },
          "line2": {
            "$ref": "#/components/schemas/String64"
          },
          "line3": {
            "$ref": "#/components/schemas/String64"
          },
          "postalCode": {
            "description": "Postal code",
            "maxLength": 16,
            "type": "string"
          },
          "region": {
            "$ref": "#/components/schemas/String64"
          }
        },
        "title": "Address",
        "type": "object"
      },
      "BusinessCustomer": {
        "description": "Customers that are commercial in nature are affiliated with a business entity",
        "properties": {
          "domicile": {
            "$ref": "#/components/schemas/Domicile"
          },
          "industryCode": {
            "$ref": "#/components/schemas/IndustryCode"
          },
          "name": {
            "description": "Name of business customer",
            "type": "string"
          },
          "registeredAgents": {
            "description": "A list of registered agents who act on behalf of the business customer",
            "items": {
              "$ref": "#/components/schemas/CustomerName"
            },
            "type": "array"
          },
          "registeredId": {
            "description": "The registered tax identification number (TIN) or other identifier of business customer",
            "type": "string"
          }
        },
        "title": "Business Customer entity",
        "type": "object"
      },
      "BusinessOrConsumer": {
        "description": "Indicator if parent entity is a consumer or business",
        "enum": [
          "BUSINESS",
          "CONSUMER"
        ],
        "title": "Business or Consumer Type",
        "type": "string"
      },
      "Contacts": {
        "description": "Contains all contact details for individual or business",
        "properties": {
          "addresses": {
            "description": "Array of the contact physical addresses",
            "items": {
              "$ref": "#/components/schemas/DeliveryAddress"
            },
            "type": "array"
          },
          "emails": {
            "description": "Array of the contact email addresses",
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "telephones": {
            "description": "Array of the contact telephone numbers",
            "items": {
              "$ref": "#/components/schemas/TelephoneNumber"
            },
            "type": "array"
          }
        },
        "title": "Contacts entity",
        "type": "object"
      },
      "ContentTypes": {
        "description": "Types of document formats. (Suggested values)",
        "enum": [
          "application/json",
          "application/pdf",
          "application/zip",
          "image/gif",
          "image/jpeg",
          "image/png",
          "image/tiff"
        ],
        "title": "Content Types",
        "type": "string"
      },
      "Customer": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Person"
          },
          {
            "properties": {
              "accounts": {
                "description": "List of accounts related to this customer",
                "items": {
                  "$ref": "#/components/schemas/CustomerToAccountRelationship"
                },
                "type": "array"
              },
              "businessCustomer": {
                "$ref": "#/components/schemas/BusinessCustomer"
              },
              "customerId": {
                "$ref": "#/components/schemas/Identifier"
              },
              "customerStartDate": {
                "$ref": "#/components/schemas/DateString"
              },
              "lastActivityDate": {
                "$ref": "#/components/schemas/DateString"
              },
              "name": {
                "$ref": "#/components/schemas/CustomerName"
              },
              "type": {
                "$ref": "#/components/schemas/BusinessOrConsumer"
              }
            },
            "type": "object"
          }
        ],
        "description": "Represents a customer",
        "title": "Customer entity",
        "type": "object"
      },
      "CustomerName": {
        "allOf": [
          {
            "$ref": "#/components/schemas/IndividualName"
          },
          {
            "properties": {
              "company": {
                "description": "Company name",
                "type": "string"
              },
              "prefix": {
                "description": "Name prefix, e.g. Mr.",
                "type": "string"
              }
            },
            "type": "object"
          }
        ],
        "description": "The name of an individual in their role as a customer",
        "title": "Customer Name entity",
        "type": "object"
      },
      "CustomerToAccountRelationship": {
        "description": "Describes an account related to a customer",
        "properties": {
          "accountId": {
            "$ref": "#/components/schemas/Identifier"
          },
          "links": {
            "$ref": "#/components/schemas/HateoasLinks"
          },
          "relationship": {
            "$ref": "#/components/schemas/AccountHolderRelationship"
          }
        },
        "title": "Customer to Account Relationship entity",
        "type": "object"
      },
      "Customers": {
        "description": "List of customers",
        "properties": {
          "customers": {
            "description": "Array of customers",
            "items": {
              "$ref": "#/components/schemas/Customer"
            },
            "type": "array"
          },
          "links": {
            "$ref": "#/components/schemas/PageMetadataLinks"
          },
          "page": {
            "$ref": "#/components/schemas/PageMetadata"
          }
        },
        "title": "Customers Entity",
        "type": "object"
      },
      "DateString": {
        "description": "ISO 8601 full-date in format 'YYYY-MM-DD' according to [IETF RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339.html#section-5.6)",
        "example": "2021-07-15",
        "format": "date",
        "maxLength": 10,
        "title": "Date String",
        "type": "string"
      },
      "DeliveryAddress": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Address"
          },
          {
            "properties": {
              "type": {
                "$ref": "#/components/schemas/DeliveryAddressType"
              }
            },
            "type": "object"
          }
        ],
        "description": "A delivery address and its location type",
        "title": "Delivery Address",
        "type": "object"
      },
      "DeliveryAddressType": {
        "description": "The location type of an address",
        "enum": [
          "BUSINESS",
          "DELIVERY",
          "HOME",
          "MAILING"
        ],
        "title": "Delivery Address Type",
        "type": "string"
      },
      "Domicile": {
        "description": "Country and region of country for the legal jurisdiction of an entity",
        "properties": {
          "country": {
            "$ref": "#/components/schemas/Iso3166CountryCode"
          },
          "region": {
            "$ref": "#/components/schemas/String64"
          }
        },
        "title": "Domicile entity",
        "type": "object"
      },
      "Error": {
        "description": "An error entity which can be used at the API level for error responses or at the account level to indicate a problem specific to a particular account. See the error codes and descriptions defined in the latest FDX API Specification document, section 6.2 Errors",
        "properties": {
          "code": {
            "description": "Error code defined by FDX API Specification or Data Provider indicating the error situation which has occurred",
            "type": "string"
          },
          "debugMessage": {
            "description": "Message used to debug the root cause of the error. Contents should not be used in consumer's business logic. Can change at any time and should only be used for consumer to communicate with the data provider about an issue. Provider can include an error GUID in message for their use.",
            "type": "string"
          },
          "message": {
            "description": "End user displayable information which might help the customer diagnose an error",
            "type": "string"
          }
        },
        "title": "Error",
        "type": "object"
      },
      "FapiInteractionId": {
        "description": "Universally unique identifier for this interaction, used across all FDX API requests and responses",
        "example": "c770aef3-6784-41f7-8e0e-ff5f97bddb3a",
        "format": "uuid",
        "maxLength": 36,
        "minLength": 36,
        "title": "FAPI Interaction ID",
        "type": "string"
      },
      "HateoasLink": {
        "description": "REST application constraint (Hypermedia As The Engine Of Application State)",
        "properties": {
          "action": {
            "$ref": "#/components/schemas/HttpAction"
          },
          "href": {
            "description": "URL to invoke the action on the resource",
            "example": "https://api.fi.com/fdx/v4/accounts/12345",
            "format": "uri-reference",
            "type": "string"
          },
          "rel": {
            "description": "Relation of this link to its containing entity, as defined by and with many example relation values at [IETF RFC5988](https://datatracker.ietf.org/doc/html/rfc5988)",
            "type": "string"
          },
          "types": {
            "description": "Content-types that can be used in the Accept header",
            "items": {
              "$ref": "#/components/schemas/ContentTypes"
            },
            "type": "array"
          }
        },
        "required": [
          "href"
        ],
        "title": "HATEOAS Link",
        "type": "object"
      },
      "HateoasLinks": {
        "description": "Links relative to this containing entity",
        "items": {
          "$ref": "#/components/schemas/HateoasLink"
        },
        "title": "HATEOAS Links array",
        "type": "array"
      },
      "HttpAction": {
        "description": "HTTP Methods to use for requests",
        "enum": [
          "DELETE",
          "GET",
          "PATCH",
          "POST",
          "PUT"
        ],
        "title": "HTTP Action Type",
        "type": "string"
      },
      "Identifier": {
        "description": "Value for a unique identifier",
        "maxLength": 256,
        "title": "Identifier",
        "type": "string"
      },
      "IndividualName": {
        "description": "First name, middle initial, last name, suffix fields",
        "properties": {
          "first": {
            "description": "First name",
            "type": "string"
          },
          "last": {
            "description": "Last name",
            "type": "string"
          },
          "middle": {
            "description": "Middle initial",
            "type": "string"
          },
          "suffix": {
            "description": "Generational or academic suffix",
            "type": "string"
          }
        },
        "title": "Individual name",
        "type": "object"
      },
      "IndustryClassificationSystem": {
        "description": "The Industry Classification System containing the industry code for customer.\n\n  | Value | Description |\n  |-----|-----|\n  | BCLASS | [Bloomberg Classification System](https://www.bloomberg.com/professional/product/reference-data/) |\n  | BICS | [Bloomberg Industry Classification System](https://www.bloomberg.com/professional/product/reference-data/) |\n  | GICS | [Global Industry Classification System](https://www.msci.com/our-solutions/indexes/gics) |\n  | MOODYS | Moody's Industry Classification |\n  | NAICS | [North American Industry Classification System](https://www.naics.com) |\n  | OTHER | Any other set of industry classification codes |\n  | SIC | [Standard Industry Classification system](https://www.osha.gov/pls/imis/sicsearch.html) |",
        "enum": [
          "BCLASS",
          "BICS",
          "GICS",
          "MOODYS",
          "NAICS",
          "OTHER",
          "SIC"
        ],
        "title": "Industry Classification System",
        "type": "string"
      },
      "IndustryCode": {
        "description": "Industry code and type",
        "properties": {
          "code": {
            "description": "Code value",
            "type": "string"
          },
          "type": {
            "$ref": "#/components/schemas/IndustryClassificationSystem"
          }
        },
        "title": "Industry code",
        "type": "object"
      },
      "Iso3166CountryCode": {
        "description": "ISO 3166-1 alpha-2 codes as of April 5, 2023, from officially assigned Country Codes on [ISO Online Browsing Platform](https://www.iso.org/obp/ui/). Change log is at [ISO 3166 Maintenance Agency](https://www.iso.org/fr/committee/48750.html?t=3V3rukDb61p05Wd6ojyTRvE0S3Yg_fZgUjrLjHWcd9-mDmTKHOGjbX3nEJ3SqHar&view=documents#section-isodocuments-top)",
        "enum": [
          "AD",
          "AE",
          "AF",
          "AG",
          "AI",
          "AL",
          "AM",
          "AO",
          "AQ",
          "AR",
          "AS",
          "AT",
          "AU",
          "AW",
          "AX",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BL",
          "BM",
          "BN",
          "BO",
          "BQ",
          "BR",
          "BS",
          "BT",
          "BV",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CC",
          "CD",
          "CF",
          "CG",
          "CH",
          "CI",
          "CK",
          "CL",
          "CM",
          "CN",
          "CO",
          "CR",
          "CU",
          "CV",
          "CW",
          "CX",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "EH",
          "ER",
          "ES",
          "ET",
          "FI",
          "FJ",
          "FK",
          "FM",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GF",
          "GG",
          "GH",
          "GI",
          "GL",
          "GM",
          "GN",
          "GP",
          "GQ",
          "GR",
          "GS",
          "GT",
          "GU",
          "GW",
          "GY",
          "HK",
          "HM",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IM",
          "IN",
          "IO",
          "IQ",
          "IR",
          "IS",
          "IT",
          "JE",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KP",
          "KR",
          "KW",
          "KY",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MF",
          "MG",
          "MH",
          "MK",
          "ML",
          "MM",
          "MN",
          "MO",
          "MP",
          "MQ",
          "MR",
          "MS",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NC",
          "NE",
          "NF",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NU",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PF",
          "PG",
          "PH",
          "PK",
          "PL",
          "PM",
          "PN",
          "PR",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RE",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SD",
          "SE",
          "SG",
          "SH",
          "SI",
          "SJ",
          "SK",
          "SL",
          "SM",
          "SN",
          "SO",
          "SR",
          "SS",
          "ST",
          "SV",
          "SX",
          "SY",
          "SZ",
          "TC",
          "TD",
          "TF",
          "TG",
          "TH",
          "TJ",
          "TK",
          "TL",
          "TM",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UM",
          "US",
          "UY",
          "UZ",
          "VA",
          "VC",
          "VE",
          "VG",
          "VI",
          "VN",
          "VU",
          "WF",
          "WS",
          "YE",
          "YT",
          "ZA",
          "ZM",
          "ZW"
        ],
        "title": "ISO 3166 Country Code",
        "type": "string"
      },
      "PageMetadata": {
        "description": "Offset IDs for paginated result sets",
        "properties": {
          "nextOffset": {
            "description": "Opaque identifier. Does not need to be numeric or have any specific pattern. Implementation specific",
            "example": "2",
            "type": "string"
          },
          "prevOffset": {
            "description": "Opaque identifier. Does not need to be numeric or have any specific pattern. Implementation specific",
            "example": "1",
            "type": "string"
          },
          "totalElements": {
            "description": "Total number of elements",
            "example": 3,
            "type": "integer"
          }
        },
        "title": "Page Metadata",
        "type": "object"
      },
      "PageMetadataLinks": {
        "description": "Resource URLs for retrieving next or previous datasets",
        "properties": {
          "next": {
            "$ref": "#/components/schemas/HateoasLink"
          },
          "prev": {
            "$ref": "#/components/schemas/HateoasLink"
          }
        },
        "title": "Page Metadata Links",
        "type": "object"
      },
      "Person": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Contacts"
          },
          {
            "properties": {
              "dateOfBirth": {
                "$ref": "#/components/schemas/DateString"
              },
              "governmentId": {
                "description": "A federal (such as passport) or state (such as driver's license) issued identifier",
                "type": "string"
              },
              "taxId": {
                "description": "Country specific Tax Id associated with this customer (SIN or NAS in Canada, SSN or TIN in US, etc.)",
                "type": "string"
              },
              "taxIdCountry": {
                "$ref": "#/components/schemas/Iso3166CountryCode"
              }
            },
            "type": "object"
          }
        ],
        "description": "Represents a person",
        "title": "Person entity",
        "type": "object"
      },
      "String64": {
        "description": "String of maximum length 64",
        "maxLength": 64,
        "title": "String 64",
        "type": "string"
      },
      "TelephoneNumber": {
        "description": "Standard for international phone numbers",
        "properties": {
          "country": {
            "description": "Country calling codes defined by ITU-T recommendations E.123 and E.164",
            "maxLength": 3,
            "type": "string"
          },
          "number": {
            "description": "Telephone subscriber number defined by ITU-T recommendation E.164",
            "maxLength": 15,
            "pattern": "\\d+",
            "type": "string"
          },
          "type": {
            "$ref": "#/components/schemas/TelephoneNumberType"
          }
        },
        "title": "Telephone Number",
        "type": "object"
      },
      "TelephoneNumberType": {
        "description": "Purpose or type of telephone number",
        "enum": [
          "BUSINESS",
          "CELL",
          "FAX",
          "HOME"
        ],
        "title": "Telephone Number Type",
        "type": "string"
      }
    },
    "headers": {
      "x-fapi-interaction-id": {
        "description": "Unique identifier for this interaction",
        "example": "c770aef3-6784-41f7-8e0e-ff5f97bddb3a",
        "schema": {
          "$ref": "#/components/schemas/FapiInteractionId"
        }
      }
    },
    "parameters": {
      "FapiInteractionIdHeader": {
        "description": "Unique identifier for this interaction",
        "example": "c770aef3-6784-41f7-8e0e-ff5f97bddb3a",
        "in": "header",
        "name": "x-fapi-interaction-id",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/FapiInteractionId"
        }
      },
      "FdxApiActorTypeHeader": {
        "description": "Identifies whether the customer is present (USER) or it is a BATCH operation",
        "example": "BATCH",
        "in": "header",
        "name": "FDX-API-Actor-Type",
        "schema": {
          "$ref": "#/components/schemas/ActorType"
        }
      },
      "LimitQuery": {
        "description": "Number of elements that the consumer wishes to receive. Providers should implement reasonable default/maximum/minimum values based on their internal architecture and update their documentation accordingly",
        "in": "query",
        "name": "limit",
        "schema": {
          "type": "integer"
        }
      },
      "OffsetQuery": {
        "description": "Opaque cursor used by the provider to send the next set of records",
        "in": "query",
        "name": "offset",
        "schema": {
          "type": "string"
        }
      }
    },
    "securitySchemes": {
      "OAuthFapi1Advanced": {
        "description": "This authorization protocol uses FAPI Security Profile 1.0 Part Two — Advanced. To be used with the FDX API customer data domains. In addition, these operations employ the FDX User Consent framework for permissioned data sharing.\nClient must comply with [5.2.3 Confidential client](https://openid.net/specs/openid-financial-api-part-2-1_0.html#confidential-client). Authorization server must comply with the [5.2.2 Authorization server](https://openid.net/specs/openid-financial-api-part-2-1_0.html#authorization-server).\nClient, authorization server and resource server requirements described in full by:\n  * [FAPI Security Profile 1.0 Part Two — Advanced](https://openid.net/specs/openid-financial-api-part-2-1_0.html)\n  * FDX API Security Model specification published with the FDX API\n\nConsent User Experience and Issuance described by:\n  * FDX User Experience Guidelines published with the FDX API\n  * Consent API operations and data structures published within the FDX API",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://auth.fi.com/fdx/v6/par",
            "scopes": {
              "fdx:accountbasic:read": "Scope authorizing retrieval of account display name, masked account number, type, description",
              "fdx:accountdetailed:read": "Scope authorizing retrieval of account information. Includes data from \"Basic\" + account balances, credit limits, due dates, interest rates, rewards balances, recurrences",
              "fdx:accountpayments:read": "Deprecated and replaced with `fdx:paymentsupport:read` in FDX release V6.1.0, `fdx:accountpayments:read` will be removed with V7 release",
              "fdx:bills:read": "Scope authorizing retrieval of bill payments data",
              "fdx:customercontact:read": "Scope authorizing retrieval of name, email, address, phone on file with this institution. Applies to both user and other account holders",
              "fdx:customerpersonal:read": "Scope authorizing retrieval of name, email, address, phone, DoB, tax ID, SSN on file with this institution",
              "fdx:images:read": "Scope authorizing retrieval of check and receipt images, which may include PII such as name, full account and routing number",
              "fdx:investments:read": "Scope authorizing retrieval of details about individual underlying investment positions",
              "fdx:paymentsupport:read": "Scope authorizing retrieval of full account number and payment network routing number",
              "fdx:rewards:read": "Scope authorizing retrieval of loyalty rewards programs, transactions and balances",
              "fdx:statements:read": "Scope authorizing retrieval of periodic PDF statement showing personal information, account and transaction details. May contain PII such as name, address",
              "fdx:tax:read": "Scope authorizing retrieval of information reporting tax forms and data, including any PII such as name, address, tax ID and account number",
              "fdx:transactions:read": "Scope authorizing retrieval of historical and current transactions, transaction types, amounts, dates and descriptions",
              "offline_access": "Scope authorizing the client to refresh `access_tokens` without user present",
              "openid": "Scope authorizing access to the user's identity details"
            },
            "tokenUrl": "https://auth.fi.com/fdx/v6/token"
          }
        },
        "type": "oauth2"
      },
      "jwtAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "responses": {
      "500": {
        "content": {
          "application/json": {
            "examples": {
              "Internal server error": {
                "value": {
                  "code": "500",
                  "debugMessage": "Data Provider's custom developer-level error details for troubleshooting",
                  "message": "Internal server error"
                }
              }
            },
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        },
        "description": "Catch-all exception where request was not processed due to an internal outage/issue. Consider other more specific errors before using this error",
        "headers": {
          "x-fapi-interaction-id": {
            "$ref": "#/components/headers/x-fapi-interaction-id"
          }
        }
      },
      "501": {
        "content": {
          "application/json": {
            "examples": {
              "FdxVersion not supported or not implemented": {
                "value": {
                  "code": "1106",
                  "debugMessage": "Data Provider's custom developer-level error details for troubleshooting",
                  "message": "FdxVersion not supported or not implemented"
                }
              }
            },
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        },
        "description": "Error when FdxVersion in Header is not one of those implemented at backend",
        "headers": {
          "x-fapi-interaction-id": {
            "$ref": "#/components/headers/x-fapi-interaction-id"
          }
        }
      },
      "503": {
        "content": {
          "application/json": {
            "examples": {
              "Scheduled Maintenance": {
                "value": {
                  "code": "503",
                  "debugMessage": "Data Provider's custom developer-level error details for troubleshooting",
                  "message": "Scheduled Maintenance"
                }
              }
            },
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        },
        "description": "System is down for maintenance",
        "headers": {
          "x-fapi-interaction-id": {
            "$ref": "#/components/headers/x-fapi-interaction-id"
          }
        }
      }
    }
  },
  "x-tyk-api-gateway": {
    "info": {
      "dbId": "6952ba3886dfb800016245c0",
      "id": "7f36dab385094ba44a2a9e66299ebcaa",
      "orgId": "5e9d9544a1dcd60001d0ed20",
      "name": "FDX V6.2.0 Customer API",
      "state": {
        "active": true,
        "internal": false
      }
    },
    "middleware": {
      "global": {
        "contextVariables": {
          "enabled": true
        },
        "pluginConfig": {
          "driver": "grpc"
        },
        "postAuthenticationPlugins": [
          {
            "enabled": true,
            "functionName": "IdempotencyCheck",
            "path": "",
            "requireSession": true
          }
        ],
        "prePlugins": [
          {
            "enabled": true,
            "functionName": "DPoPCheck",
            "path": "",
            "rawBodyOnly": true
          }
        ],
        "responsePlugins": [
          {
            "enabled": true,
            "functionName": "IdempotencyResponse",
            "path": "",
            "requireSession": true
          }
        ],
        "trafficLogs": {
          "enabled": true
        }
      }
    },
    "server": {
      "authentication": {
        "enabled": true,
        "securitySchemes": {
          "jwtAuth": {
            "header": {
              "enabled": true,
              "name": "Authorization"
            },
            "identityBaseField": "sub",
            "policyFieldName": "pol",
            "enabled": true,
            "defaultPolicies": [
              "68bb84368f572b0001f1c7c0"
            ],
            "signingMethod": "ecdsa",
            "source": "aHR0cDovL2tleWNsb2FrOjgxODAvcmVhbG1zL2ZhcGktZGVtby9wcm90b2NvbC9vcGVuaWQtY29ubmVjdC9jZXJ0cw=="
          }
        }
      },
      "gatewayTags": {
        "enabled": true,
        "tags": [
          "tyk-gateway"
        ]
      },
      "listenPath": {
        "strip": true,
        "value": "/fdxapi"
      }
    },
    "upstream": {
      "proxy": {
        "enabled": false,
        "url": ""
      },
      "url": "http://host.docker.internal:8090/fdxapi"
    }
  }
}